Fortigate IP: 260.1.1.1
Response data:
Test 1 URL: https://260.1.1.1:10443/api/v2/monitor/system/status

Test 1 Error: HTTPSConnectionPool(host='260.1.1.1', port=10443): Max retries exceeded with url: /api/v2/monitor/system/status (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022E42530150>: Failed to resolve '260.1.1.1' ([Errno 11001] getaddrinfo failed)"))
Response Data: API call failed with the keyFortigate IP: 260.1.1.1
No username provided, cannot log in.
